CREATE TABLE product
(
  ID INT PRIMARY KEY NOT NULL IDENTITY,
  NAME VARCHAR(200) NOT NULL,
  MATERIAL VARCHAR(200) NOT NULL,
  AMOUNT INT NOT NULL
);

CREATE TABLE supply
(
  ID INT PRIMARY KEY NOT NULL IDENTITY,
  MATERIAL VARCHAR(200) NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  AMOUNT INT NOT NULL
);